import { Event, Ticket, User } from './types';

export const mockUsers: User[] = [
  { id: 'u1', name: 'Admin Demo', email: 'admin@gravity.app', role: 'admin' },
  { id: 'u2', name: 'Staff Demo', email: 'staff@gravity.app', role: 'staff' },
  { id: 'u3', name: 'María García', email: 'maria@email.com', role: 'client' },
];

export const mockEvents: Event[] = [
  {
    id: 'e1',
    title: 'NEON PULSE',
    description: 'Una experiencia audiovisual inmersiva con los mejores DJs de la escena electrónica underground. Espacio transformado con instalaciones de luz y sonido envolvente.',
    date: '2026-04-15',
    time: '23:00',
    venue: 'Warehouse District',
    city: 'Madrid',
    imageUrl: '',
    capacity: 500,
    ticketsSold: 342,
    priceTiers: [
      { id: 't1', name: 'Early Bird', price: 15, maxQuantity: 100, sold: 100, expiresAt: '2026-03-15' },
      { id: 't2', name: 'General', price: 25, maxQuantity: 300, sold: 200 },
      { id: 't3', name: 'VIP', price: 50, maxQuantity: 100, sold: 42 },
    ],
    organizerId: 'u1',
    status: 'upcoming',
    category: 'Electrónica',
  },
  {
    id: 'e2',
    title: 'SONIC GARDEN',
    description: 'Festival al aire libre con música en vivo, food trucks artesanales y zona chill. Un jardín sonoro donde la naturaleza y la música convergen.',
    date: '2026-05-20',
    time: '16:00',
    venue: 'Parque Central',
    city: 'Barcelona',
    imageUrl: '',
    capacity: 2000,
    ticketsSold: 850,
    priceTiers: [
      { id: 't4', name: 'Early Bird', price: 20, maxQuantity: 500, sold: 500, expiresAt: '2026-04-01' },
      { id: 't5', name: 'General', price: 35, maxQuantity: 1200, sold: 300 },
      { id: 't6', name: 'Premium', price: 75, maxQuantity: 300, sold: 50 },
    ],
    organizerId: 'u1',
    status: 'upcoming',
    category: 'Festival',
  },
  {
    id: 'e3',
    title: 'DEEP STATE',
    description: 'Sesión de techno oscuro en un bunker subterráneo. Aforo reducido para una experiencia íntima y cruda. Solo para los valientes.',
    date: '2026-03-28',
    time: '00:00',
    venue: 'El Bunker',
    city: 'Valencia',
    imageUrl: '',
    capacity: 150,
    ticketsSold: 140,
    priceTiers: [
      { id: 't7', name: 'Única', price: 18, maxQuantity: 150, sold: 140 },
    ],
    organizerId: 'u1',
    status: 'upcoming',
    category: 'Techno',
  },
  {
    id: 'e4',
    title: 'AURORA NIGHTS',
    description: 'Una velada elegante con música house melódica, cócteles artesanales y vistas panorámicas de la ciudad desde la terraza más alta.',
    date: '2026-06-10',
    time: '21:00',
    venue: 'Sky Terrace Hotel W',
    city: 'Sevilla',
    imageUrl: '',
    capacity: 300,
    ticketsSold: 78,
    priceTiers: [
      { id: 't8', name: 'Early Bird', price: 30, maxQuantity: 80, sold: 78 },
      { id: 't9', name: 'Standard', price: 45, maxQuantity: 150, sold: 0 },
      { id: 't10', name: 'Table VIP', price: 120, maxQuantity: 70, sold: 0 },
    ],
    organizerId: 'u1',
    status: 'upcoming',
    category: 'House',
  },
];

export const mockTickets: Ticket[] = [
  {
    id: 'tk1',
    eventId: 'e1',
    eventTitle: 'NEON PULSE',
    eventDate: '2026-04-15',
    eventTime: '23:00',
    eventVenue: 'Warehouse District',
    buyerName: 'María García',
    buyerEmail: 'maria@email.com',
    tierName: 'VIP',
    price: 50,
    qrCode: 'GRAV-TK1-NEONPULSE-VIP-2026',
    status: 'valid',
    purchasedAt: '2026-03-01T10:30:00Z',
  },
  {
    id: 'tk2',
    eventId: 'e2',
    eventTitle: 'SONIC GARDEN',
    eventDate: '2026-05-20',
    eventTime: '16:00',
    eventVenue: 'Parque Central',
    buyerName: 'María García',
    buyerEmail: 'maria@email.com',
    tierName: 'General',
    price: 35,
    qrCode: 'GRAV-TK2-SONICGARDEN-GEN-2026',
    status: 'valid',
    purchasedAt: '2026-03-02T14:00:00Z',
  },
];
